spring.application.name=demo
spring.datasource.url=jdbc:mysql://practise.c1usaakm00au.us-east-1.rds.amazonaws.com:3306/practise?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=admin
spring.datasource.password=admin123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
port=8081